version: '3.8'

services:
  bot-caixinha:
    build: .
    container_name: bot-caixinha
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./backup:/app/backup
    env_file:
      - .env